apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: solar
  namespace: argocd
spec:
  clusterResourceBlacklist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceNamespaces:
  - argocd
  - custom-namespace
