---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: proxy-impersonate
rules:
- apiGroups: [""]
  resources:
  - users
  - groups
  verbs:
  - impersonate
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: proxy-impersonate
roleRef:
  kind: ClusterRole
  name:  proxy-impersonate
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:capsule-system
  apiGroup: rbac.authorization.k8s.io
