---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: solar
  labels:
    app.kubernetes.io/type: dev
  annotations:
    argo.addons.projectcapsule.dev/read-only: "true"
    argo.addons.projectcapsule.dev/decouple: "false"
spec:
  owners:
  - name: solar-users
    kind: Group
  - name: alice
    kind: User
  additionalRoleBindings:
  - clusterRoleName: tenant-viewer
    subjects:
    - kind: User
      name: bob
---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: wind
  labels:
    app.kubernetes.io/type: prod
spec:
  owners:
  - name: wind-users
    kind: Group
  - name: bob
    kind: User
---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: oil
  labels:
    app.kubernetes.io/type: dev
    hello: "there"
    nyan: "dann"
  annotations:
    argo.addons.projectcapsule.dev/read-only: "false"
    argo.addons.projectcapsule.dev/decouple: "true"
spec:
  owners:
  - name: solar-users
    kind: Group
  - name: alice
    kind: User
  additionalRoleBindings:
  - clusterRoleName: tenant-viewer
    subjects:
    - name: bob
      kind: User
