run:
  allow-parallel-runners: true
issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: true
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
linters-settings:
  goheader:
    template: |-
      Copyright 2024 Peak Scale
      SPDX-License-Identifier: Apache-2.0
linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
