project_name: capsule-argo-addon
env:
  - COSIGN_EXPERIMENTAL=true
  - GO111MODULE=on
before:
  hooks:
    - go mod download
gomod:
  proxy: false

builds:
  - main: ./cmd
    binary: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - >-
        -X github.com/peak-scale/{{ .ProjectName }}/cmd.Version={{ .Tag }}
        -X github.com/peak-scale/{{ .ProjectName }}/cmd.GitCommit={{ .Commit }}
        -X github.com/peak-scale/{{ .ProjectName }}/cmd.BuildDate={{ .Date }}
release:
  footer: |
    **Full Changelog**: https://github.com/peak-scale/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    **Docker Images**
    - `ghcr.io/peak-scale/{{ .ProjectName }}:{{ .Tag }}`
    - `ghcr.io/peak-scale/{{ .ProjectName }}:latest`

    **Helm Chart**
    View this release on [Artifact Hub](https://artifacthub.io/packages/helm/capsule-argo-addon/capsule-argo-addon)

    [![Artifact Hub](https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/capsule-argo-addon)](https://artifacthub.io/packages/search?repo=capsule-argo-addon)

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
  groups:
  - title: Dependency updates
    regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
    order: 300
  - title: 'New Features'
    regexp: '^.*?feat(\([[:word:]]+\))?!?:.+$|^feat:.+$'
    order: 100
  - title: 'Bug fixes'
    regexp: '^.*?fix(\([[:word:]]+\))?!?:.+$|^fix:.+$'
    order: 200
  - title: 'Documentation updates'
    regexp: '^.*?doc(\([[:word:]]+\))?!?:.+$|^doc:.+$'
    order: 400
  - title: 'Build process updates'
    regexp: '^.*?build(\([[:word:]]+\))?!?:.+$|^build:.+$'
    order: 400
  - title: Other work
    order: 9999
sboms:
  - artifacts: archive
signs:
- cmd: cosign
  args:
  - "sign-blob"
  - "--output-signature=${signature}"
  - "${artifact}"
  - "--yes"
  artifacts: all
