---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - config.projectcapsule.dev
  resources:
  - argocdaddons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.projectcapsule.dev
  resources:
  - argocdaddons/finalizers
  verbs:
  - update
- apiGroups:
  - config.projectcapsule.dev
  resources:
  - argocdaddons/status
  verbs:
  - get
  - patch
  - update
