{{- if $.Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" . }}-rbac-list
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm.fullname" . }}-rbac-list
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helm.fullname" . }}-rbac-list
subjects:
  - kind: Group
    name: system:serviceaccounts:{{ $.Release.Namespace }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}