{{- if $.Values.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-webhook-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
{{- end }}