name: Integration Test

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

permissions: read-all

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check secret
        id: checksecret
        uses: peak-scale/github-actions/exists@38322faabccd75abfa581c435e367d446b6d2c3b # v0.1.0
        with:
          value: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: '1.19'
      - name: Run integration tests
        run: |
          make integration-test
      - name: Upload coverage reports to Codecov
        if: steps.checksecret.outputs.result == 'true'
        uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e # v5.1.1
        with:
          files: ./test/integration/cover.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
