name: Integration Test

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

permissions: read-all

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check secret
        id: checksecret
        uses: peak-scale/github-actions/exists@38322faabccd75abfa581c435e367d446b6d2c3b # v0.1.0
        with:
          value: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '1.19'
      - name: Run integration tests
        run: |
          make integration-test
      - name: Upload coverage reports to Codecov
        if: steps.checksecret.outputs.result == 'true'
        uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
        with:
          files: ./test/integration/cover.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
