name: e2e
permissions: {}

on:
  pull_request:
    branches:
      - "*"
    paths:
      - '.github/workflows/e2e.yml'
      - 'api/**'
      - 'cmd/**'
      - 'internal/**'
      - 'e2e/*'
      - '.ko.yaml'
      - 'go.*'
      - 'main.go'
      - 'Makefile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kind:
    name: Kubernetes
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - ""
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
      - name: e2e testing
        run: KIND_K8S_VERSION="${{ matrix.k8s-version }}" make e2e
